nats:
    image: 'nats:0.8.0'
    entrypoint: "/gnatsd -D"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
gateway:
    build: ./gateway
    ports:
        - "4000:4000"
    links: 
        - nats:nats-server
author:
    build: ./author
    links: 
        - nats:nats-server
book:
    build: ./book
    links: 
        - nats:nats-server
